# Generated by Django 5.0.3 on 2024-11-28 08:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_accessories_alter_product_interface_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ir_distance',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None),
        ),
    ]
